name: im
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  dio: any
  web_socket_channel: any
  sqflite: any
  shared_preferences: any
  protoc_plugin: any
  contactor_picker: any
  extended_text_field: any
  audioplayers: 0.19.0
  flutter_ffmpeg: ^0.4.2
  video_player: any

  flutter: 
    sdk: flutter
dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/emoji/
    - assets/sounds/
    - assets/videos/

