name: im
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.0
  dio: 4.0.0
  web_socket_channel: 2.1.0
  sqflite: ^1.3.0
  shared_preferences: ^2.0.6
  protoc_plugin: 20.0.0
  flutter: 
    sdk: flutter
dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/emoji/

